#ifndef R16_CCU_H
#define R16_CCU_H

#include <cstdint>

class CCU {
public:
    CCU();
    void init();

    uint32_t PPL_CPUX_CTRL_REG;
    uint32_t PPL_AUDIO_CTRL_REG;
    uint32_t PPL_VE_CTRL_REG;
    uint32_t PPL_DDR0_CTRL_REG;
    uint32_t PPL_PERIPH_CTRL_REG;
    uint32_t PPL_GPU_CTRL_REG;
    uint32_t PPL_MIPI_CTRL_REG;
    uint32_t PPL_HSIC_CTRL_REG;
    uint32_t PPL_DE_CTRL_REG;
    uint32_t PPL_DDR1_CTRL_REG;
    uint32_t CPU_AXI_CFG_REG;
    uint16_t AHB1_APB1_CFG_REG;
    uint32_t APB2_CFG_REG;
    uint32_t BUS_CLK_GATING_REG0;
    uint32_t BUS_CLK_GATING_REG1;
    uint16_t BUS_CLK_GATING_REG2;
    uint32_t BUS_CLK_GATING_REG3;
    uint32_t NAND_CLK_REG;
    uint32_t SDMMC0_CLK_REG;
    uint32_t SDMMC1_CLK_REG;
    uint32_t SDMMC2_CLK_REG;
    uint32_t CE_CLK_REG;
    uint32_t SPI0_CLK_REG;
    uint32_t DAUDIO0_CLK_REG;
    uint32_t DAUDIO1_CLK_REG;
    uint32_t USBPHY_CFG_REG;
    uint32_t DRAM_CFG_REG;
    uint16_t PPL_DDR_CFG_REG;
    uint32_t MBUS_RST_REG;
    uint32_t DRAM_CLK_GATING_REG;
    uint32_t BE_CLK_REG;
    uint32_t FE_CLK_REG;
    uint32_t LCD_CH0_CLK_REG;
    uint32_t LCD_CH1_CLK_REG;
    uint32_t CSI_CLK_REG;
    uint32_t VE_CLK_REG;
    uint32_t AC_DIG_CLK_REG;
    uint32_t AVS_CLK_REG;
    uint32_t MBUS_CLK_REG;
    uint32_t MIPI_DSI_CLK_REG;
    uint32_t DRC_CLK_REG;
    uint32_t GPU_CLK_REG;
    uint32_t ATS_CLK_REG;
    uint16_t PLL_STABLE_TIME_REG0;
    uint16_t PLL_STABLE_TIME_REG1;
    uint32_t PLL_CPUX_BIAS_CFG;
    uint32_t PLL_AUDIO_BIAS_REG;
    uint32_t PLL_VIDEO_BIAS_REG;
    uint32_t PLL_VE_BIAS_REG;
    uint32_t PLL_DDR0_BIAS_REG;
    uint32_t PLL_PERIPH_BIAS_REG;
    uint32_t PLL_GPU_BIAS_REG;
    uint32_t PLL_MIPI_BIAS_REG;
    uint32_t PLL_HSIC_BIAS_REG;
    uint32_t PLL_DE_BIAS_REG;
    uint32_t PLL_DDR1_BIAS_REG;
    uint32_t PLL_CPUX_TUN_REG;
    uint32_t PLL_DDR0_TUN_REG;
    uint32_t PLL_MIPI_TUN_REG;
    uint32_t PLL_CPUX_PAT_CTRL_REG;
    uint32_t PLL_AUDIO_PAT_CTRL_REG;
    uint32_t PLL_VIDEO_PAT_CTRL_REG;
    uint32_t PLL_VE_PAT_CTRL_REG;
    uint32_t PLL_DDR0_PAT_CTRL_REG;
    uint32_t PLL_GPU_PAT_CTRL_REG;
    uint32_t PLL_MIPI_PAT_CTRL_REG;
    uint32_t PLL_HSIC_PAT_CTRL_REG;
    uint32_t PLL_DE_PAT_CTRL_REG;
    uint32_t PLL_DDR1_PAT_CTRL_REG0;
    uint32_t PLL_DDR1_PAT_CTRL_REG1;
    uint32_t BUS_SOFT_RST_REG0;
    uint32_t BUS_SOFT_RST_REG1;
    uint8_t BUS_SOFT_RST_REG2;
    uint16_t BUS_SOFT_RST_REG3;
    uint32_t BUS_SOFT_RST_REG4;
};
#endif //R16_CCU_H
